Fix tests and chef18 fixes
sous-chefs/stunnel pull request #88
Opened 2023-02-09 12:10 UTC by logicsys

# Description

Fix test cookbook by updating nginx dependency & creating an nginx_service resource

add unified_mode true & String type to connect & accept properties for connection resource

## Issues Resolved

None

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2023-02-09 22:35 UTC, Stromweld commented
This needs the .github/workflows/ci.yml file updated to use the singular linting jobs and should look similar to this one https://github.com/sous-chefs/php/blob/main/.github/workflows/ci.yml

2023-02-10 14:49 UTC, Stromweld requested changes

2023-02-10 14:49 UTC, Stromweld commented on .github/workflows/ci.yml
> +    needs: [mdl, yamllint, lint-unit]
lint-unit replaces the need for mdl, yamllint, and delivery jobs.

2023-02-10 16:16 UTC, Stromweld requested changes

2023-02-10 16:16 UTC, Stromweld commented on resources/connection.rb
> +property :accept, String, required: true
These actually should probably be both string or integer `[String, Integer]` then the test cookbooks don't need to be updated with quotes when it's just a port number.

2023-02-15 18:00 UTC, logicsys commented
Hmm, not sure why those last 5 tests are failing, working fine locally for me

2023-02-15 20:04 UTC, damacus commented
Some of the yum and apt repositories have been getting hammered today. I had 1/2 of my suites fail because of that.

2023-02-19 17:37 UTC, logicsys commented
think there was something up with the dokken ubuntu-1604 image and systemd support, have dropped that from the tests anyway, and added ubuntu-2004, ubuntu-2204 & rockylinux-8

2023-02-20 14:27 UTC, damacus commented on test/cookbooks/test/metadata.rb
> +depends 'nginx', '~> 12.1.1'
Ah missed this. We can unpin this completely so we find the breakage sooner.

2023-02-20 14:27 UTC, damacus requested changes
Just one change on the Nginx dep and we're good to go!

2023-02-26 20:50 UTC, logicsys commented
unpinned, that should be everything done finally ha

2023-02-27 11:09 UTC, damacus approved these changes

2023-02-27 11:10 UTC, damacus approved these changes

2023-02-27 11:10 UTC, merged

2023-02-27 11:10 UTC, kitchen-porter commented
Released as: [5.0.0](https://github.com/sous-chefs/stunnel/releases/tag/5.0.0)